Repository Siren-repo/Siren, pull requests merged in 2023-10, with the labels that each got.

#16 아이템관리 API 구현
  build.gradle
  src/main/java/com/devlop/siren/domain/category/controller/CategoryController.java
  src/main/java/com/devlop/siren/domain/category/dto/request/CategoryCreateRequest.java
  src/main/java/com/devlop/siren/domain/category/dto/response/CategoriesResponse.java
  src/main/java/com/devlop/siren/domain/category/dto/response/CategoryItemsResponse.java
  src/main/java/com/devlop/siren/domain/category/dto/response/CategoryResponse.java
  src/main/java/com/devlop/siren/domain/category/entity/Category.java
  src/main/java/com/devlop/siren/domain/category/entity/CategoryType.java
  src/main/java/com/devlop/siren/domain/category/repository/CategoryRepository.java
  src/main/java/com/devlop/siren/domain/category/service/CategoryService.java
  src/main/java/com/devlop/siren/domain/item/controller/ItemController.java
  src/main/java/com/devlop/siren/domain/item/dto/request/DefaultOptionCreateRequest.java
  src/main/java/com/devlop/siren/domain/item/dto/request/ItemCreateRequest.java
  src/main/java/com/devlop/siren/domain/item/dto/request/NutritionCreateRequest.java
  src/main/java/com/devlop/siren/domain/item/dto/response/DefaultOptionResponse.java
  src/main/java/com/devlop/siren/domain/item/dto/response/ItemDetailResponse.java
  src/main/java/com/devlop/siren/domain/item/dto/response/ItemResponse.java
  src/main/java/com/devlop/siren/domain/item/dto/response/NutritionDetailResponse.java
  src/main/java/com/devlop/siren/domain/item/entity/AllergyType.java
  src/main/java/com/devlop/siren/domain/item/entity/DefaultOption.java
  src/main/java/com/devlop/siren/domain/item/entity/Item.java
  src/main/java/com/devlop/siren/domain/item/entity/Nutrition.java
  src/main/java/com/devlop/siren/domain/item/entity/SizeType.java
  src/main/java/com/devlop/siren/domain/item/repository/DefaultOptionRepository.java
  src/main/java/com/devlop/siren/domain/item/repository/ItemRepository.java
  src/main/java/com/devlop/siren/domain/item/repository/NutritionRepository.java
  src/main/java/com/devlop/siren/domain/item/service/ItemService.java
  src/main/java/com/devlop/siren/domain/item/service/ItemServiceImpl.java
  src/main/java/com/devlop/siren/domain/item/utils/AllergyConverter.java
  src/main/java/com/devlop/siren/global/common/response/ApiResponse.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/main/java/com/devlop/siren/global/exception/ExceptionControllerAdvice.java
  src/main/java/com/devlop/siren/global/exception/GlobalException.java
  src/test/java/com/devlop/siren/SirenApplicationTests.java
  src/test/java/com/devlop/siren/category/controller/CategoryControllerTest.java
  src/test/java/com/devlop/siren/category/service/CategoryServiceTest.java
  src/test/java/com/devlop/siren/item/controller/ItemControllerTest.java
  src/test/java/com/devlop/siren/item/service/ItemServiceImplTest.java
Labels: 🔨 Refactor, ✨ Feature

#13 회원가입 API 구현
  build.gradle
  src/main/java/com/devlop/siren/SirenApplication.java
  src/main/java/com/devlop/siren/domain/user/controller/UserController.java
  src/main/java/com/devlop/siren/domain/user/domain/AllergyType.java
  src/main/java/com/devlop/siren/domain/user/domain/User.java
  src/main/java/com/devlop/siren/domain/user/domain/UserRole.java
  src/main/java/com/devlop/siren/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/devlop/siren/domain/user/repository/UserRepository.java
  src/main/java/com/devlop/siren/domain/user/service/UserService.java
  src/main/java/com/devlop/siren/domain/user/util/AllergyConverter.java
  src/main/java/com/devlop/siren/domain/user/util/validator/KoreanNickname.java
  src/main/java/com/devlop/siren/domain/user/util/validator/KoreanNicknameValidator.java
  src/main/java/com/devlop/siren/global/common/BaseEntity.java
  src/main/java/com/devlop/siren/global/common/response/ApiResponse.java
  src/main/java/com/devlop/siren/global/configuration/JpaAuditingConfig.java
  src/main/java/com/devlop/siren/global/configuration/SecurityConfig.java
  src/main/java/com/devlop/siren/global/exception/ExceptionControllerAdvice.java
  src/main/resources/application.yml
  src/test/java/com/devlop/siren/category/controller/CategoryControllerTest.java
  src/test/java/com/devlop/siren/fixture/UserFixture.java
  src/test/java/com/devlop/siren/item/controller/ItemControllerTest.java
  src/test/java/com/devlop/siren/unit/controller/UserControllerTest.java
  src/test/java/com/devlop/siren/unit/domain/UserTest.java
  src/test/java/com/devlop/siren/unit/repository/UserRepositoryTest.java
  src/test/java/com/devlop/siren/unit/service/UserServiceTest.java
Labels: ✨ Feature

#21 Revert "filter chain 설정 수정 "
  src/main/java/com/devlop/siren/domain/user/controller/UserController.java
  src/main/java/com/devlop/siren/domain/user/domain/AllergyType.java
  src/main/java/com/devlop/siren/domain/user/domain/User.java
  src/main/java/com/devlop/siren/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/devlop/siren/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/devlop/siren/domain/user/service/UserService.java
  src/main/java/com/devlop/siren/domain/user/util/AllergyConverter.java
  src/main/java/com/devlop/siren/domain/user/util/validator/KoreanNickname.java
  src/main/java/com/devlop/siren/domain/user/util/validator/KoreanNicknameValidator.java
  src/main/java/com/devlop/siren/global/configuration/AuthenticationConfig.java
  src/main/java/com/devlop/siren/global/configuration/filter/JwtTokenFilter.java
  src/test/java/com/devlop/siren/fixture/UserFixture.java
  src/test/java/com/devlop/siren/unit/controller/UserControllerTest.java
  src/test/java/com/devlop/siren/unit/domain/UserTest.java
  src/test/java/com/devlop/siren/unit/repository/UserRepositoryTest.java
  src/test/java/com/devlop/siren/unit/service/UserServiceTest.java
  src/test/java/com/devlop/siren/user/controller/UserControllerTest.java
  src/test/java/com/devlop/siren/user/repository/UserRepositoryTest.java
  src/test/java/com/devlop/siren/user/service/UserServiceTest.java
Labels: 🐞 Bug

#24 아이템, 카테고리 인증정보 구현
  src/main/java/com/devlop/siren/domain/category/controller/CategoryController.java
  src/main/java/com/devlop/siren/domain/item/controller/ItemController.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/main/java/com/devlop/siren/global/util/UserInformation.java
  src/test/java/com/devlop/siren/category/controller/CategoryControllerTest.java
  src/test/java/com/devlop/siren/item/controller/ItemControllerTest.java
Labels: 🔨 Refactor, ✅ Test, ✨ Feature

#25 매장 관리 API (권한에 따른 매장 API 리팩토링)
  build.gradle
  src/main/java/com/devlop/siren/domain/store/controller/StoreController.java
  src/main/java/com/devlop/siren/domain/store/domain/Store.java
  src/main/java/com/devlop/siren/domain/store/dto/request/StoreRegisterRequest.java
  src/main/java/com/devlop/siren/domain/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/devlop/siren/domain/store/dto/response/StoreResponse.java
  src/main/java/com/devlop/siren/domain/store/repository/StoreRepository.java
  src/main/java/com/devlop/siren/domain/store/service/StoreService.java
  src/main/java/com/devlop/siren/domain/store/utils/GeocodingApi.java
  src/main/java/com/devlop/siren/global/common/response/ApiResponse.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/main/resources/application.yml
  src/test/java/com/devlop/siren/store/controller/StoreControllerTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetNearByStoreTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetServiceTest.java
  src/test/java/com/devlop/siren/store/service/StoreServiceTest.java
Labels: 🔨 Refactor, ✅ Test, ✨ Feature
