Repository Siren-repo/Siren, pull requests merged in 2023-12, with the labels that each got.

#39 장바구니 API 구현
  src/main/java/com/devlop/siren/domain/cart/controller/CartController.java
  src/main/java/com/devlop/siren/domain/cart/dto/CartDto.java
  src/main/java/com/devlop/siren/domain/cart/service/CartService.java
  src/main/java/com/devlop/siren/domain/item/dto/request/ItemCreateRequest.java
  src/main/java/com/devlop/siren/domain/item/entity/option/OptionDetails.java
  src/main/java/com/devlop/siren/domain/order/dto/request/CustomOptionRequest.java
  src/main/java/com/devlop/siren/domain/order/dto/request/OrderItemRequest.java
  src/main/java/com/devlop/siren/domain/stock/service/StockService.java
  src/main/java/com/devlop/siren/domain/user/dto/UserDetailsDto.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/main/java/com/devlop/siren/global/configuration/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/devlop/siren/cart/controller/CartControllerTest.java
  src/test/java/com/devlop/siren/cart/service/CartServiceTest.java
  src/test/java/com/devlop/siren/category/service/CategoryServiceTest.java
  src/test/java/com/devlop/siren/fixture/ItemFixture.java
  src/test/java/com/devlop/siren/fixture/UserFixture.java
  src/test/java/com/devlop/siren/item/service/ItemServiceImplTest.java
  src/test/java/com/devlop/siren/stock/service/StockServiceTest.java
  src/test/java/com/devlop/siren/store/service/StoreServiceTest.java
Labels: 🔨 Refactor, ✨ Feature

#43 refactor: 권한확인 로직을 인터셉터에서 처리
  src/main/java/com/devlop/siren/domain/store/controller/StoreController.java
  src/main/java/com/devlop/siren/domain/store/domain/Store.java
  src/main/java/com/devlop/siren/domain/store/dto/request/StoreRegisterRequest.java
  src/main/java/com/devlop/siren/domain/store/dto/request/StoreUpdateRequest.java
  src/main/java/com/devlop/siren/domain/store/dto/response/StoreResponse.java
  src/main/java/com/devlop/siren/domain/store/service/StoreService.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/main/java/com/devlop/siren/global/configuration/SecurityConfig.java
  src/main/java/com/devlop/siren/global/configuration/filter/JwtTokenFilter.java
  src/main/java/com/devlop/siren/global/util/Permission.java
  src/main/java/com/devlop/siren/global/util/PermissionInterceptor.java
  src/test/java/com/devlop/siren/stock/service/StockServiceTest.java
  src/test/java/com/devlop/siren/store/controller/StoreControllerTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetNearByStoreTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetServiceTest.java
  src/test/java/com/devlop/siren/store/service/StoreServiceTest.java
Labels: 🔨 Refactor

#40 feat: 주문취소, 주문상태변경 API 구현
  src/main/java/com/devlop/siren/domain/order/controller/OrderController.java
  src/main/java/com/devlop/siren/domain/order/domain/Order.java
  src/main/java/com/devlop/siren/domain/order/domain/OrderItem.java
  src/main/java/com/devlop/siren/domain/order/domain/OrderStatus.java
  src/main/java/com/devlop/siren/domain/order/domain/option/CustomOption.java
  src/main/java/com/devlop/siren/domain/order/domain/option/FoodOption.java
  src/main/java/com/devlop/siren/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/com/devlop/siren/domain/order/dto/request/OrderItemRequest.java
  src/main/java/com/devlop/siren/domain/order/dto/request/OrderStatusRequest.java
  src/main/java/com/devlop/siren/domain/order/dto/response/CustomOptionResponse.java
  src/main/java/com/devlop/siren/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/devlop/siren/domain/order/repository/CustomOptionRepository.java
  src/main/java/com/devlop/siren/domain/order/repository/OrderItemRepository.java
  src/main/java/com/devlop/siren/domain/order/repository/OrderRepository.java
  src/main/java/com/devlop/siren/domain/order/service/OrderService.java
  src/main/java/com/devlop/siren/domain/stock/entity/Stock.java
  src/main/java/com/devlop/siren/global/common/response/ResponseCode.java
  src/test/java/com/devlop/siren/fixture/OrderFixture.java
  src/test/java/com/devlop/siren/order/controller/OrderControllerTest.java
  src/test/java/com/devlop/siren/order/service/OrderServiceTest.java
  src/test/java/com/devlop/siren/order/service/OrderUseCaseTest.java
  src/test/java/com/devlop/siren/stock/service/StockServiceTest.java
Labels: ✨ Feature

#45 권한테스트 및 리팩토링
  src/main/java/com/devlop/siren/domain/cart/service/CartService.java
  src/main/java/com/devlop/siren/domain/category/controller/CategoryController.java
  src/main/java/com/devlop/siren/domain/category/entity/Category.java
  src/main/java/com/devlop/siren/domain/category/service/CategoryService.java
  src/main/java/com/devlop/siren/domain/item/controller/ItemController.java
  src/main/java/com/devlop/siren/domain/item/entity/Item.java
  src/main/java/com/devlop/siren/domain/item/service/ItemService.java
  src/main/java/com/devlop/siren/domain/item/service/ItemServiceImpl.java
  src/main/java/com/devlop/siren/domain/stock/controller/StockController.java
  src/main/java/com/devlop/siren/domain/stock/service/StockService.java
  src/main/java/com/devlop/siren/domain/store/domain/Store.java
  src/test/java/com/devlop/siren/cart/controller/CartControllerTest.java
  src/test/java/com/devlop/siren/category/controller/CategoryControllerTest.java
  src/test/java/com/devlop/siren/category/service/CategoryServiceTest.java
  src/test/java/com/devlop/siren/fixture/ItemFixture.java
  src/test/java/com/devlop/siren/fixture/OrderFixture.java
  src/test/java/com/devlop/siren/fixture/StoreFixture.java
  src/test/java/com/devlop/siren/item/controller/ItemControllerTest.java
  src/test/java/com/devlop/siren/item/service/ItemServiceImplTest.java
  src/test/java/com/devlop/siren/order/service/OrderServiceTest.java
  src/test/java/com/devlop/siren/order/service/OrderUseCaseTest.java
  src/test/java/com/devlop/siren/stock/controller/StockControllerTest.java
  src/test/java/com/devlop/siren/stock/service/StockServiceTest.java
  src/test/java/com/devlop/siren/store/controller/StoreControllerTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetNearByStoreTest.java
  src/test/java/com/devlop/siren/store/service/StoreGetServiceTest.java
  src/test/java/com/devlop/siren/store/service/StoreServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#46 refactor: 권한체크 로직 변경으로 인한 Store, Order 수정
  src/main/java/com/devlop/siren/domain/order/controller/OrderController.java
  src/main/java/com/devlop/siren/domain/order/dto/request/OrderItemRequest.java
  src/main/java/com/devlop/siren/domain/order/service/OrderService.java
  src/main/java/com/devlop/siren/domain/store/controller/StoreController.java
  src/main/java/com/devlop/siren/domain/store/service/StoreService.java
  src/test/java/com/devlop/siren/order/controller/OrderControllerTest.java
  src/test/java/com/devlop/siren/order/service/OrderServiceTest.java
  src/test/java/com/devlop/siren/stock/service/StockServiceTest.java
  src/test/java/com/devlop/siren/store/controller/StoreControllerTest.java
  src/test/java/com/devlop/siren/store/service/StoreServiceTest.java
Labels: 🔨 Refactor, ✅ Test
